#!/usr/bin/env python3
"""Batch 4 / z4 taken-states (items 16-17): ov-key-taken, ov-tag-taken.

Deterministic PIL ($0): wall regenerated by row-interp between valid stone
neighbors + donor-strip high-frequency grain (the F5 screwdriver recipe that
passed fix-pass review); wood sliver behind the key bow/bit filled by
column-interp. Revealed hook nail for the key = donor copy of the tag's nail
(flipped). Tag removal keeps its nail. Wide patch + CU echo patches are
resize-chain-consistent with their CU bases; every patch seam-checked <= 24.
"""
import json
import os
import sys

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from l2_b4_states import seam, CU_W, CU_H

A2 = r"C:\Users\shaim\escape-room\specs\assets\level-2"
Z4 = os.path.join(A2, "z4")
Z4_WIDE = os.path.join(Z4, "v-vault-interior", "z4-vault-base@3x.png")
Z4_STATES = os.path.join(Z4, "v-vault-interior", "states")
Z4_JSON = os.path.join(Z4, "z4-state-overlays.json")
Z4_CU = {
    "cu-key-hook": (700, 280, 1620, 970),
    "cu-tag-nail": (500, 350, 1400, 1025),
}


def rowfill(a, mask, grain_src=None, grain_amp=0.5):
    out = a.copy()
    h, w = mask.shape
    for y in range(h):
        row = mask[y]
        if not row.any():
            continue
        xs = np.nonzero(row)[0]
        runs = np.split(xs, np.nonzero(np.diff(xs) > 1)[0] + 1)
        for run in runs:
            x0, x1 = run[0], run[-1]
            xl, xr = x0 - 1, x1 + 1
            if xl < 0 and xr >= w:
                continue
            if xl < 0:
                out[y, x0:x1 + 1] = out[y, xr]
            elif xr >= w:
                out[y, x0:x1 + 1] = out[y, xl]
            else:
                t = np.linspace(0, 1, x1 - x0 + 3)[1:-1][:, None]
                out[y, x0:x1 + 1] = out[y, xl] * (1 - t) + out[y, xr] * t
    if grain_src is not None:
        g = grain_src - np.asarray(
            Image.fromarray(np.clip(grain_src, 0, 255).astype(np.uint8)).filter(
                ImageFilter.GaussianBlur(6)), np.float32)
        tile = np.concatenate([g, g[:, ::-1]], axis=1)
        tile = np.concatenate([tile, tile[::-1]], axis=0)
        ty = np.arange(h) % tile.shape[0]
        tx = np.arange(w) % tile.shape[1]
        gg = tile[np.ix_(ty, tx)]
        out = out + gg * grain_amp * mask[..., None]
    return out


def colfill(a, mask):
    out = a.copy()
    h, w = mask.shape
    for x in range(w):
        col = mask[:, x]
        if not col.any():
            continue
        ys = np.nonzero(col)[0]
        runs = np.split(ys, np.nonzero(np.diff(ys) > 1)[0] + 1)
        for run in runs:
            y0, y1 = run[0], run[-1]
            yl, yr = y0 - 1, y1 + 1
            if yl < 0 and yr >= h:
                continue
            if yl < 0:
                out[y0:y1 + 1, x] = out[yr, x]
            elif yr >= h:
                out[y0:y1 + 1, x] = out[yl, x]
            else:
                t = np.linspace(0, 1, y1 - y0 + 3)[1:-1][:, None]
                out[y0:y1 + 1, x] = out[yl, x] * (1 - t) + out[yr, x] * t
    return out


def z4_json(update):
    m = json.load(open(Z4_JSON)) if os.path.exists(Z4_JSON) else {}
    m.update(update)
    with open(Z4_JSON, "w") as f:
        json.dump(m, f, indent=1)


def z4_save(name, wide_new, wide_base, rect, cu_name, note):
    os.makedirs(Z4_STATES, exist_ok=True)
    x0, y0, x1, y1 = rect
    patch = wide_new.crop(rect)
    sc = seam(wide_base, patch.convert("RGB"), rect)
    assert sc <= 24, f"{name} wide seam {sc:.1f}"
    patch.convert("RGB").save(os.path.join(Z4_STATES, name + "-wide@3x.png"))
    fx0, fy0, fx1, fy1 = Z4_CU[cu_name]
    scale = CU_W / (fx1 - fx0)
    cu_base = Image.open(os.path.join(
        Z4, "v-vault-interior", cu_name + "@3x.png")).convert("RGB")
    cu_new = wide_new.crop((fx0, fy0, fx1, fy1)).resize(
        (CU_W, CU_H), Image.LANCZOS)
    cx0, cy0 = max(0, int((x0 - fx0) * scale)), max(0, int((y0 - fy0) * scale))
    cx1 = min(CU_W, int((x1 - fx0) * scale) + 1)
    cy1 = min(CU_H, int((y1 - fy0) * scale) + 1)
    cpatch = cu_new.crop((cx0, cy0, cx1, cy1))
    sc2 = seam(cu_base, cpatch, (cx0, cy0, cx1, cy1))
    assert sc2 <= 24, f"{name} CU seam {sc2:.1f}"
    cpatch.save(os.path.join(Z4_STATES, name + "@3x.png"))
    z4_json({name: {
        "base": cu_name, "rect_3x": [cx0, cy0, cx1, cy1],
        "wide_base": "z4-vault-base", "wide_rect_3x": list(rect),
        "note": note}})
    print(f"  {name}: wide seam {sc:.1f} / CU seam {sc2:.1f} PASS")


def main():
    wide = Image.open(Z4_WIDE).convert("RGB")
    a = np.asarray(wide, np.float32)

    # ---------- key taken ----------
    mask_im = Image.new("L", wide.size, 0)
    d = ImageDraw.Draw(mask_im)
    d.ellipse([1028, 448, 1238, 648], fill=255)
    d.rectangle([1068, 620, 1142, 845], fill=255)
    d.rectangle([1012, 830, 1215, 940], fill=255)
    mask_im = mask_im.filter(ImageFilter.MaxFilter(9))
    m = np.asarray(mask_im) > 100
    stone = m.copy()
    stone[:, 1198:] = False
    wood = m & ~stone
    grain = a[300:420, 880:1000]
    filled = rowfill(a, stone, grain_src=grain, grain_amp=0.45)
    filled = colfill(filled, wood)
    out = Image.fromarray(np.clip(filled, 0, 255).astype(np.uint8))
    nail = wide.crop((820, 442, 892, 502)).transpose(Image.FLIP_LEFT_RIGHT)
    nm = Image.new("L", nail.size, 0)
    dd = ImageDraw.Draw(nm)
    dd.ellipse([6, 4, nail.width - 6, nail.height - 4], fill=255)
    nm = nm.filter(ImageFilter.GaussianBlur(3))
    out.paste(nail, (1064, 438), nm)
    z4_save("ov-key-taken", out, wide, (1000, 415, 1255, 955), "cu-key-hook",
            "winding key taken: wall stone row-interp + wood column fill; "
            "revealed iron nail (donor: tag nail, flipped); square-bit rhyme "
            "leaves with the key")

    # ---------- tag taken ----------
    mask_im = Image.new("L", wide.size, 0)
    d = ImageDraw.Draw(mask_im)
    d.rectangle([742, 620, 952, 945], fill=255)
    d.polygon([(756, 540), (806, 462), (890, 462), (880, 640), (790, 660)],
              fill=255)
    d.polygon([(700, 560), (790, 700), (760, 940), (700, 940)], fill=255)
    mask_im = mask_im.filter(ImageFilter.MaxFilter(7))
    keep = Image.new("L", wide.size, 0)
    dk = ImageDraw.Draw(keep)
    dk.ellipse([816, 440, 894, 504], fill=255)
    mask = (np.asarray(mask_im) > 100) & ~(np.asarray(keep) > 40)
    grain = a[320:430, 560:690]
    filled = rowfill(a, mask, grain_src=grain, grain_amp=0.45)
    out = Image.fromarray(np.clip(filled, 0, 255).astype(np.uint8))
    z4_save("ov-tag-taken", out, wide, (690, 425, 970, 965), "cu-tag-nail",
            "return tag + rope loop taken (incl. wall shadow); iron nail "
            "kept with its own small shadow")


if __name__ == "__main__":
    main()
