import SpriteKit
import Combine

/// Wires a `RoomScene` for a given `ViewID` to `GameState` + `PuzzleEngine`: builds the
/// hotspot list, resolves the current texture set from state, and handles taps/drops by
/// dispatching to the appropriate PuzzleEngine call. One coordinator instance per active
/// view; the room navigator (SwiftUI) creates/destroys these as the player moves between
/// views, but GameState itself is shared/long-lived (owned by LevelSession).
///
/// Hotspot pixel rects for state-image overlays come from
/// EscapeRoom/Resources/GameAssets/level-1/overlays.json (authoritative, generated by
/// the asset pipeline). Hotspots for plain tap targets that have no overlay entry
/// (item pickups drawn directly on the base plate, dial/tile positions inside a
/// close-up) are hand-placed conservative rectangles per the style guide's dual-safe-
/// zone + 44pt hit-target rules; see implementation-notes.md "hotspot placement" for
/// the explicit list of judgment calls made here since the manifest does not carry
/// pixel rects for every interactive element (only for compositable overlays).
final class RoomSceneCoordinator: ObservableObject {
    let viewID: ViewID
    let scene: RoomScene
    let state: GameState
    private var cancellable: AnyCancellable?

    /// Transient (non-persisted) per-scene UI state.
    @Published var lastBrewOutcome: PuzzleEngine.BrewOutcome?
    @Published var justPoppedClock: Bool = false
    @Published var showTerminalRefusal: Bool = false

    init(viewID: ViewID, state: GameState, size: CGSize) {
        self.viewID = viewID
        self.state = state
        self.scene = RoomScene(viewID: viewID, size: size)
        configure()
        scene.onHotspotTap = { [weak self] id in self?.handleTap(id) }
        scene.onItemDropped = { [weak self] itemID, hotspotID in self?.handleDrop(itemID, on: hotspotID) }
        cancellable = state.objectWillChange.sink { [weak self] _ in
            DispatchQueue.main.async { self?.refresh() }
        }
    }

    // MARK: - Setup

    private func configure() {
        switch viewID {
        case .hearth: configureHearth()
        case .study: configureStudy()
        case .entry: configureEntry()
        case .bench: configureBench()
        case .cabinet: configureCabinet()
        case .cellar: configureCellar()
        case .alcove: configureAlcove()
        }
        refresh()
    }

    func refresh() {
        switch viewID {
        case .hearth: refreshHearth()
        case .study: refreshStudy()
        case .entry: refreshEntry()
        case .bench: refreshBench()
        case .cabinet: refreshCabinet()
        case .cellar: refreshCellar()
        case .alcove: refreshAlcove()
        }
    }

    // MARK: - v-hearth (z1)

    private func configureHearth() {
        scene.setBaseTexture("z1-hearth-base")
        scene.configureHotspots([
            Hotspot(id: "poker", 0.14, 0.40, 0.10, 0.55),
            Hotspot(id: "ash", 0.30, 0.55, 0.20, 0.30),
            Hotspot(id: "clock", 0.45, 0.10, 0.16, 0.30),
            Hotspot(id: "bellows", 0.62, 0.20, 0.10, 0.25),
            Hotspot(id: "lintel", 0.45, 0.05, 0.20, 0.10),
            Hotspot(id: "rug", 0.10, 0.72, 0.60, 0.28),
            Hotspot(id: "trapdoor-dial", 0.30, 0.75, 0.35, 0.20),
        ])
    }

    private func refreshHearth() {
        scene.setOverlay("poker", imageNamed: RoomVisuals.pokerTaken(state) ? "ov-poker-taken" : nil,
                          rectNormalized: overlayRect("z1/v-hearth", "ov-poker-taken"))
        scene.setOverlay("rug", imageNamed: RoomVisuals.rugMoved(state) ? "ov-rug-moved" : nil,
                          rectNormalized: overlayRect("z1/v-hearth", "ov-rug-moved"))
        scene.setOverlay("trapdoor", imageNamed: RoomVisuals.trapdoorOpen(state) ? "ov-trapdoor-open" : nil,
                          rectNormalized: overlayRect("z1/v-hearth", "ov-trapdoor-open"))
    }

    // MARK: - v-study (z1)

    private func configureStudy() {
        scene.setBaseTexture("z1-study-base")
        scene.configureHotspots([
            Hotspot(id: "grimoire", 0.30, 0.55, 0.30, 0.35),
            Hotspot(id: "triptych", 0.55, 0.15, 0.30, 0.25),
            Hotspot(id: "flowerpot", 0.08, 0.55, 0.12, 0.20),
            Hotspot(id: "rune-tile-1", 0.70, 0.14, 0.10, 0.19),
            Hotspot(id: "rune-tile-2", 0.70, 0.36, 0.10, 0.19),
            Hotspot(id: "rune-tile-3", 0.70, 0.58, 0.10, 0.19),
            Hotspot(id: "rune-tile-4", 0.70, 0.80, 0.10, 0.19),
        ])
    }

    private func refreshStudy() {
        // Rune door: no persistent visual per-tile "pressed" latch across a full reset
        // in this build (tiles reset with a dull knock, no lockout) — pressed sprites
        // are shown transiently by the tap handler, not derived from persisted state.
    }

    // MARK: - v-entry (z1)

    private func configureEntry() {
        scene.setBaseTexture("z1-entry-base")
        scene.configureHotspots([
            Hotspot(id: "door-lock", 0.40, 0.35, 0.20, 0.40),
            Hotspot(id: "rusted-key", 0.15, 0.30, 0.08, 0.20),
            Hotspot(id: "windowsill", 0.65, 0.55, 0.20, 0.15),
            Hotspot(id: "cage", 0.73, 0.20, 0.25, 0.48),
            Hotspot(id: "feed-cup", 0.85, 0.45, 0.08, 0.08),
            Hotspot(id: "star-keyhole", 0.80, 0.30, 0.06, 0.06),
        ])
    }

    private func refreshEntry() {
        scene.setOverlay("vines", imageNamed: RoomVisuals.vinesState(state) == "vines-gone" ? "ov-vines-gone" : nil,
                          rectNormalized: overlayRect("z1/v-entry", "ov-vines-gone"))
        scene.setOverlay("cage", imageNamed: RoomVisuals.cageState(state) == "cage-open-empty" ? "ov-cage-open" : nil,
                          rectNormalized: overlayRect("z1/v-entry", "ov-cage-open"))
        scene.setOverlay("crow-lintel", imageNamed: RoomVisuals.crowLocation(state) == "on-lintel" ? "ov-crow-lintel" : nil,
                          rectNormalized: overlayRect("z1/v-entry", "ov-crow-lintel"))
    }

    // MARK: - v-bench (z2)

    private func configureBench() {
        scene.setBaseTexture("z2-bench-base")
        scene.configureHotspots([
            Hotspot(id: "cauldron", 0.10, 0.35, 0.30, 0.40),
            Hotspot(id: "floor-bellows", 0.45, 0.55, 0.15, 0.30),
            Hotspot(id: "ladle", 0.20, 0.45, 0.15, 0.20),
            Hotspot(id: "mortar", 0.60, 0.55, 0.20, 0.25),
        ])
    }

    private func refreshBench() {
        scene.setOverlay("flame", imageNamed: flameOverlayName(), rectNormalized: overlayRect("z2/v-bench", "ov-flame\(max(state.data.cauldronFlameStage,1))"))
    }

    private func flameOverlayName() -> String? {
        let stage = state.data.cauldronFlameStage
        guard stage > 0 else { return nil }
        return "ov-flame\(min(stage, 3))"
    }

    // MARK: - v-cabinet (z2)

    private func configureCabinet() {
        scene.setBaseTexture("z2-cabinet-base")
        scene.configureHotspots([
            Hotspot(id: "sun-slot", 0.15, 0.20, 0.10, 0.15),
            Hotspot(id: "moon-slot", 0.28, 0.20, 0.10, 0.15),
            Hotspot(id: "potion-shelf", 0.50, 0.15, 0.25, 0.30),
            Hotspot(id: "astrolabe", 0.72, 0.55, 0.24, 0.35),
            Hotspot(id: "window", 0.80, 0.10, 0.18, 0.30),
        ])
    }

    private func refreshCabinet() {
        scene.setOverlay("slots", imageNamed: RoomVisuals.cabinetDoorState(state) ? "ov-slots-seated" : nil,
                          rectNormalized: overlayRect("z2/v-cabinet", "ov-slots-seated"))
        scene.setOverlay("cabinet-door", imageNamed: RoomVisuals.cabinetDoorState(state) ? "ov-cab-open" : nil,
                          rectNormalized: overlayRect("z2/v-cabinet", "ov-cab-open"))
        scene.setOverlay("adrawer", imageNamed: RoomVisuals.astrolabeDrawerOpen(state) ? "ov-adrawer-open" : nil,
                          rectNormalized: overlayRect("z2/v-cabinet", "ov-adrawer-open"))
    }

    // MARK: - v-cellar (z3)

    private func configureCellar() {
        scene.setBaseTexture("z3-cellar-base")
        scene.configureHotspots([
            Hotspot(id: "barrel", 0.75, 0.48, 0.24, 0.50),
            Hotspot(id: "drawer", 0.28, 0.52, 0.16, 0.22),
            Hotspot(id: "shelf", 0.05, 0.30, 0.35, 0.55),
            Hotspot(id: "hook", 0.20, 0.25, 0.10, 0.15),
            Hotspot(id: "winch", 0.10, 0.12, 0.18, 0.32),
            Hotspot(id: "mirror", 0.48, 0.55, 0.20, 0.42),
        ])
    }

    private func refreshCellar() {
        scene.setOverlay("barrel", imageNamed: RoomVisuals.barrelState(state), rectNormalized: overlayRect("z3/v-cellar", RoomVisuals.barrelState(state)))
        scene.setOverlay("drawer", imageNamed: RoomVisuals.drawerState(state), rectNormalized: overlayRect("z3/v-cellar", RoomVisuals.drawerState(state)))
        if RoomVisuals.crankFitted(state) {
            scene.setOverlay("crank", imageNamed: "ov-crank-fitted", rectNormalized: overlayRect("z3/v-cellar", "ov-crank-fitted"))
        } else {
            scene.setOverlay("crank", imageNamed: nil, rectNormalized: .zero)
        }
        let mirrorOverlay = state.data.mirrorDetent == 3 ? "ov-mirror-d3" : (state.data.mirrorDetent == 2 ? "ov-mirror-d2" : nil)
        scene.setOverlay("mirror", imageNamed: mirrorOverlay, rectNormalized: mirrorOverlay.map { overlayRect("z3/v-cellar", $0) } ?? .zero)
        // Base plate itself swaps for the beam/shelf composite states (whole-frame
        // variants, not small overlays) — see z3-cellar-beam-*/shelf-slid plates.
        switch RoomVisuals.beamVisual(state) {
        case .none:
            scene.setBaseTexture(RoomVisuals.shelfSlid(state) ? "z3-cellar-shelf-slid" : "z3-cellar-base")
        case .floorBeam:
            scene.setBaseTexture(RoomVisuals.shelfSlid(state) ? "z3-cellar-beam-floor-shelf-slid" : "z3-cellar-beam-floor")
        case .blockedOnShelf:
            scene.setBaseTexture("z3-cellar-beam-blocked")
        case .intoAlcove:
            scene.setBaseTexture("z3-cellar-beam-alcove")
        }
    }

    // MARK: - v-alcove (z4)

    private func configureAlcove() {
        scene.setBaseTexture("z4-alcove-base")
        scene.configureHotspots([
            Hotspot(id: "planter", 0.15, 0.45, 0.30, 0.40),
            Hotspot(id: "statue-key", 0.55, 0.20, 0.20, 0.35),
        ])
    }

    private func refreshAlcove() {
        let planter = RoomVisuals.planterState(state)
        let keyTaken = RoomVisuals.cageKeyTaken(state)
        switch (planter, keyTaken) {
        case ("closed", _): scene.setBaseTexture("z4-alcove-base")
        case ("trembling", _): scene.setBaseTexture("z4-alcove-trembling")
        case ("blooming", false): scene.setBaseTexture("z4-alcove-blooming")
        case ("blooming", true): scene.setBaseTexture("z4-alcove-blooming-keytaken")
        case ("picked", false): scene.setBaseTexture("z4-alcove-picked")
        case ("picked", true): scene.setBaseTexture("z4-alcove-picked-keytaken")
        default: scene.setBaseTexture("z4-alcove-base")
        }
    }

    // MARK: - Tap / drop routing

    /// Entry point for drops originating in the SwiftUI inventory bar (resolved to a
    /// scene-space hotspot id by the caller). Public because GameRoomView drives it
    /// directly from a global drag-gesture coordinate conversion.
    func handleExternalDrop(itemID: String, hotspotID: String) {
        handleDrop(itemID, on: hotspotID)
    }

    private func handleTap(_ hotspotID: String) {
        SoundManager.shared.play(.click)
        switch (viewID, hotspotID) {
        case (.hearth, "poker"):
            if !RoomVisuals.pokerTaken(state) {
                state.addItem(PuzzleGraph.ItemID.poker)
                SoundManager.shared.play(.pickup)
            }
        case (.hearth, "ash"):
            if PuzzleEngine.siftAsh(state: state) { SoundManager.shared.play(.solve) }
        case (.hearth, "rug"):
            break // free action: reveal handled by refreshHearth once z3 unlocked via dial solve
        case (.hearth, "trapdoor-dial"):
            advanceMoonDial()
        case (.entry, "rusted-key"):
            if !state.hasItem(PuzzleGraph.ItemID.rustedKey) {
                state.addItem(PuzzleGraph.ItemID.rustedKey)
                SoundManager.shared.play(.pickup)
            }
        case (.entry, "cage"):
            PuzzleEngine.triggerCrowTerminalRefusal()
            showTerminalRefusal = true
            SoundManager.shared.play(.refusal)
        case (.entry, "feed-cup"):
            PuzzleEngine.triggerCrowTerminalRefusal()
            showTerminalRefusal = true
            SoundManager.shared.play(.refusal)
        case (.entry, "star-keyhole"):
            if PuzzleEngine.unlockCage(state: state) { SoundManager.shared.play(.solve) }
        case (.study, let tile) where tile.hasPrefix("rune-tile-"):
            if let n = Int(tile.replacingOccurrences(of: "rune-tile-", with: "")),
               let rune = RuneDoorSolution.tileRune[n] {
                let result = PuzzleEngine.pressRuneTile(rune, state: state)
                switch result {
                case .solved: SoundManager.shared.play(.unlock)
                case .reset: SoundManager.shared.play(.wrong)
                case .inProgress: break
                }
            }
        case (.cabinet, "astrolabe"):
            if PuzzleEngine.selectAstrolabePlate(AstrolabeSolution.solutionPlateIndex, state: state) {
                SoundManager.shared.play(.solve)
            }
        case (.cellar, "drawer"):
            if !state.hasItem(PuzzleGraph.ItemID.spoon) {
                state.addItem(PuzzleGraph.ItemID.spoon)
                SoundManager.shared.play(.pickup)
            }
        case (.cellar, "barrel"):
            if PuzzleEngine.pryBarrel(state: state) { SoundManager.shared.play(.solve) }
        case (.cellar, "winch"):
            if PuzzleEngine.fitCrankAndTurn(state: state) { SoundManager.shared.play(.unlock) }
        case (.cellar, "mirror"):
            let next = (state.data.mirrorDetent % MirrorSolution.detentCount) + 1
            PuzzleEngine.rotateMirror(toDetent: next, state: state)
            SoundManager.shared.play(.click)
        case (.alcove, "planter"):
            if PuzzleEngine.pickBlossom(state: state) { SoundManager.shared.play(.pickup) }
        case (.alcove, "statue-key"):
            if !RoomVisuals.cageKeyTaken(state) {
                state.addItem(PuzzleGraph.ItemID.cageKey)
                SoundManager.shared.play(.pickup)
            }
        default:
            break
        }
    }

    private func advanceMoonDial() {
        // Simplified single-tap-cycles-all-three-dials affordance retained for the
        // hotspot smoke path; the production UI exposes three independent dial
        // controls (see MoonDialView) that call `state.setMoonDialPosition` directly
        // per-dial and then `PuzzleEngine.evaluateMoonDials`.
        _ = PuzzleEngine.evaluateMoonDials(state: state)
    }

    private func handleDrop(_ itemID: String, on hotspotID: String) {
        switch (viewID, hotspotID) {
        case (.entry, "feed-cup"):
            // D4 (+ D1 for the draught specifically): ANY item offered here gets the
            // identical terminal refusal; item is returned to inventory unspent.
            if itemID == PuzzleGraph.ItemID.phialDraught {
                PuzzleEngine.attemptPourDraughtAtFeedCup()
            } else {
                PuzzleEngine.triggerCrowTerminalRefusal()
            }
            showTerminalRefusal = true
            SoundManager.shared.play(.refusal)
        case (.entry, "door-lock"):
            if itemID == PuzzleGraph.ItemID.phialDraught {
                if PuzzleEngine.pourDraughtOnBasin(state: state) {
                    SoundManager.shared.play(.solve)
                }
            }
        case (.hearth, "ash"):
            if itemID == PuzzleGraph.ItemID.poker, PuzzleEngine.siftAsh(state: state) {
                SoundManager.shared.play(.solve)
            }
        case (.cellar, "barrel"):
            if itemID == PuzzleGraph.ItemID.poker, PuzzleEngine.pryBarrel(state: state) {
                SoundManager.shared.play(.solve)
            }
        case (.cellar, "hook"):
            if itemID == PuzzleGraph.ItemID.weight, PuzzleEngine.hangWeight(state: state) {
                SoundManager.shared.play(.unlock)
            }
        case (.cellar, "winch"):
            if itemID == PuzzleGraph.ItemID.crank, PuzzleEngine.fitCrankAndTurn(state: state) {
                SoundManager.shared.play(.unlock)
            }
        case (.cabinet, "sun-slot"), (.cabinet, "moon-slot"):
            attemptCabinetPlacement(itemID, slot: hotspotID)
        case (.bench, "mortar"):
            if itemID == PuzzleGraph.ItemID.blossom, PuzzleEngine.grindPaste(state: state) {
                SoundManager.shared.play(.solve)
            }
        case (.bench, "cauldron"):
            addCauldronIngredient(itemID)
        default:
            break
        }
    }

    private var pendingSunItem: String?
    private var pendingMoonItem: String?

    private func attemptCabinetPlacement(_ itemID: String, slot: String) {
        if slot == "sun-slot" { pendingSunItem = itemID } else { pendingMoonItem = itemID }
        if PuzzleEngine.placeCabinetItems(sun: pendingSunItem, moon: pendingMoonItem, state: state) {
            SoundManager.shared.play(.solve)
            pendingSunItem = nil
            pendingMoonItem = nil
        }
    }

    private func addCauldronIngredient(_ itemID: String) {
        guard BrewSolution.requiredIngredients.contains(itemID), state.hasItem(itemID) else { return }
        var ingredients = state.data.cauldronIngredients
        ingredients.insert(itemID)
        state.removeItem(itemID)
        state.setCauldronIngredients(ingredients)
    }

    // MARK: - overlay rect lookup

    private func overlayRect(_ viewKey: String, _ overlayKey: String) -> CGRect {
        OverlayRectCatalog.shared.rect(view: viewKey, overlay: overlayKey) ?? .zero
    }
}
